server:
  port: 8762
  servlet:
    context-path: /c
spring:
  application:
    name: bird-fly-animal-restapi
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



mybatis-plus:
  classpath*: mapper/**:xml




